### ISSUE TITLE
Speckle purpose/roadmap

### ISSUE THREAD

**Issue by JanFilipec** [specklesystems/speckle-docs#10]
What is the exact purpose of speckle? What is it supposed to do and is just not implemented yet and what is it not supposed to do?
I think this fundamental information is very important for anyone starting with speckle and even after quite a bit of digging I haven't found answers.
I got speckle running in blender and it looks great what I still don't know is:
Is speckle able to stream data between different supported software? So can I download the stream I created in blender to grasshopper?
I see that only geometry is supported in blender right now. So does speckle do geometry only? Or will it some day support modifiers and transformation and all the other Data present in a blender object?
People at Osarch.org are developing a BIM add-on form blender, it would be amazing to be able to share the whole bim model from blender through speckle, but is it even its intended use?

**Comment by didimitrie** [comment]
Hi @JanFilipec! All those are good points that you have raised - we'll strive to make them more clear as we go ahead! To our defence, the docs are still in WIP as well as the companion website. Most importantly, they're for V2, and I suspect you're having fun in Blender with V1. 

Re the rest of the questions, I'll answer here, but in the future Q&As like these ideally should go [into the forum](http://speckle.community). Mind you they're valid across v1/v2, and there's different nuances between them. 

> Is speckle able to stream data between different supported software? So can I download the stream I created in blender to grasshopper?

Barring any bugs, yes. See [here](https://v1.speckle.systems/docs/essentials/introduction/interop). 

> I see that only geometry is supported in blender right now. So does speckle do geometry only?

Speckle does "3d information" - that means geometry + metadata. This is a long question to unpack; but see [this](https://v1.speckle.systems/docs/developers/object-models) for 1.0, and parallel discussions re v2 [here](https://discourse.speckle.works/t/introducing-kits-2-0/710), [here](https://discourse.speckle.works/t/core-2-0-the-base-object/782) and [here](https://discourse.speckle.works/t/core-2-0-decomposition-api/911).

> Or will it some day support modifiers and transformation and all the other Data present in a blender object?

Transforms are from our end a bit of a pain. It would mean applying them in each other software we support, and that's not great; especially since Blender transforms can go way beyond simple `matrix4` ops (if I'm not mistaken). It's much easier for us to operate in "real space". 

> People at Osarch.org are developing a BIM add-on form blender, it would be amazing to be able to share the whole bim model from blender through speckle, but is it even its intended use?

Well aware of this, and I can't wait for us to push 2.0 out the door so we can look at a proper Blender integration! 

---

I'll close this issue but feel free to continue the discussion (or move it to the forum if you'd like!).

**Comment by JanFilipec** [comment]
Thanks @didimitrie ! I wanted to ask on the forum, but I could not finish the registration as I didn't receive any email to be able to confirm it (I tried having the email resent which didn't work, but eventually received a different email reminding me to confirm, so I succeeded)
I'll move to the forum now.
