### ISSUE TITLE
Listing Non-supported Elements From Revit to Speckle

### ISSUE THREAD

**Issue by kraftwerk15** [specklesystems/speckle-docs#26]
IDK if you didn't want to list them in the Docs.

I was trying to copy Scope Boxes from one project to another and was provided a warning from Speckle connector that this was not possible.

Speckle team should determine if they want to list these items out on the Documentation of items not supported. The current list did not contain Scope Boxes and was rather vague.

[https://speckle.guide/user/support-tables.html#non-supported-elements](https://speckle.guide/user/support-tables.html#non-supported-elements)

**Comment by teocomi** [comment]
Hey @kraftwerk15 we currently are only listing supported elements or the ones we're working on, anything else should be considered as non supported. The reason is that there are A LOT of types available and it's just a bit easier this way than listing them all...
In the new UI for Revit that we're rolling out soon it'll be more clear, after a conversion, to understand what was skipped because non supported or what instead failed to convert.
Let me know if it makes sense, happy to reopen this or to continue the conversation on our form if you'd like: https://speckle.community/
